### ISSUE TITLE
ParseError: not well-formed (invalid token)

### ISSUE THREAD

**Issue by BitterSweetcandyshop** [NiNiyas/autoscan#8]
I'm very confused. I assumed it ment plex token, so I went and grabbed my plex token using the plex support artical, and grabbing it from the xml url. I know it works since I use it with PlexTraktSync without issue.

I am Using an Ubuntu 20.4 server, this is an rclone sftp mount.

Here is the Error:
```
 2023-11-05 07:12:51,491 -     INFO -      PLEX [140158792364032]: Requesting section info from Plex...
 2023-11-05 07:12:51,493 -     INFO -      PLEX [140158792364032]: Requesting of section info was successful.
 2023-11-05 07:12:51,494 -    ERROR -      PLEX [140158792364032]: Issue encountered when attempting to list detailed sections info.
Traceback (most recent call last):
  File "/opt/autoscan/plex.py", line 31, in show_detailed_sections_info
    root = ElementTree.fromstring(resp.text)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1342, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```
My Config
Yes both servers have the same user, and I also mounted it so the file paths would be the same, since at the time I was moving my plex server over and wanted everything to go smoothly.
```json
{
  "DOCKER_NAME": "plex",
  "ENABLE_JOE": false,
  "ENABLE_PLEX": true,
  "GOOGLE": {
    "ALLOWED": {
      "FILE_EXTENSIONS": true,
      "FILE_EXTENSIONS_LIST": [
        "webm",
        "mkv",
        "flv",
        "vob",
        "ogv",
        "ogg",
        "drc",
        "gif",
        "gifv",
        "mng",
        "avi",
        "mov",
        "qt",
        "wmv",
        "yuv",
        "rm",
        "rmvb",
        "asf",
        "amv",
        "mp4",
        "m4p",
        "m4v",
        "mpg",
        "mp2",
        "mpeg",
        "mpe",
        "mpv",
        "m2v",
        "m4v",
        "svi",
        "3gp",
        "3g2",
        "mxf",
        "roq",
        "nsv",
        "f4v",
        "f4p",
        "f4a",
        "f4b",
        "mp3",
        "flac",
        "ts"
      ],
      "FILE_PATHS": [
        "My Drive/Media/Movies/",
        "My Drive/Media/TV/",
        "My Drive/Media/4K/"
      ],
      "MIME_TYPES": true,
      "MIME_TYPES_LIST": [
        "video"
      ]
    },
    "CLIENT_ID": "",
    "CLIENT_SECRET": "",
    "DISABLE_DISK_FILE_SIZE_CHECK": false,
    "ENABLED": false,
    "POLL_INTERVAL": 120,
    "SHOW_CACHE_LOGS": true,
    "TEAMDRIVE": false,
    "TEAMDRIVES": []
  },
  "JELLYFIN_EMBY": "jellyfin",
  "JOE_API_KEY": "",
  "JOE_HOST": "http://localhost:8096",
  "PLEX_ANALYZE_DIRECTORY": true,
  "PLEX_ANALYZE_TYPE": "basic",
  "PLEX_CHECK_BEFORE_SCAN": true,
  "PLEX_DATABASE_PATH": "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db",
  "PLEX_EMPTY_TRASH": false,
  "PLEX_EMPTY_TRASH_CONTROL_FILES": [
    "/mnt/unionfs/mounted.bin"
  ],
  "PLEX_EMPTY_TRASH_MAX_FILES": 100,
  "PLEX_EMPTY_TRASH_ZERO_DELETED": false,
  "PLEX_FIX_MISMATCHED": false,
  "PLEX_FIX_MISMATCHED_LANG": "en",
  "PLEX_LD_LIBRARY_PATH": "/usr/lib/plexmediaserver/lib",
  "PLEX_LOCAL_URL": "http://localhost:32400",
  "PLEX_SCANNER": "/usr/lib/plexmediaserver/Plex\\ Media\\ Scanner",
  "PLEX_SUPPORT_DIR": "/var/lib/plexmediaserver/Library/Application\\ Support",
  "PLEX_TOKEN": "TOKEN",
  "PLEX_USER": "plex",
  "PLEX_WAIT_FOR_EXTERNAL_SCANNERS": false,
  "RCLONE": {
    "BINARY": "/usr/bin/rclone",
    "CONFIG": "",
    "CRYPT_MAPPINGS": {},
    "RC_CACHE_REFRESH": {
      "ENABLED": true,
      "FILE_EXISTS_TO_REMOTE_MAPPINGS": {
        "/home/bittersweet/media/": [
          "/home/bittersweet/media/"
        ]
      },
      "RC_URL": "http://localhost:5572"
    }
  },
  "RUN_COMMAND_AFTER_SCAN": "",
  "RUN_COMMAND_BEFORE_SCAN": "",
  "SERVER_ALLOW_MANUAL_SCAN": false,
  "SERVER_FILE_CHECK_DELAY": 60,
  "SERVER_FILE_EXIST_PATH_MAPPINGS": {
    "/home/bittersweet/media/": [
      "/home/bittersweet/media/"
    ]
  },
  "SERVER_IGNORE_LIST": [
    "/.grab/",
    ".DS_Store",
    "Thumbs.db"
  ],
  "SERVER_IP": "0.0.0.0",
  "SERVER_MAX_FILE_CHECKS": 10,
  "SERVER_PASS": "PASS",
  "SERVER_PATH_MAPPINGS": {
    "/home/bittersweet/media/": [
      "/home/bittersweet/media/"
    ]
  },
  "SERVER_PORT": 3467,
  "SERVER_SCAN_DELAY": 180,
  "SERVER_SCAN_FOLDER_ON_FILE_EXISTS_EXHAUSTION": false,
  "SERVER_SCAN_PRIORITIES": {
    "0": [
      "home/bittersweet/media/Movies/"
    ],
    "1": [
      "/home/bittersweet/media/TV/",
      "/home/bittersweet/media/Anime"
    ],
    "2": [
      "/home/bittersweet/media/Music/"
    ]
  },
  "SERVER_USE_SQLITE": false,
  "USE_DOCKER": false,
  "USE_SUDO": true
}
```

**Comment by NiNiyas** [comment]
Hi. Sorry for taking so long to reply. Can you see your libraries when you go to `http://<plex url>/library/sections/all?X-Plex-Token=<your plex token>` ?

**Comment by charles474** [comment]
@NiNiyas I'm also gettng the same error. WIth this URL `http://<plex url>/library/sections/all?X-Plex-Token=<your plex token>`, I can see my libraries.

**Comment by NiNiyas** [comment]
Hey, this should now be fixed in the [alpha](https://github.com/NiNiyas/autoscan/tree/alpha) branch. Could you please give that a try? If you are on docker, use `ghcr.io/niniyas/autoscan:alpha_amd64` or `ghcr.io/niniyas/autoscan:alpha_arm64`, and don't forget to read the updated [readme](https://github.com/NiNiyas/autoscan/blob/alpha/README.md).
